#DEV envoirenment

app:
  message: This is the property file for the ${spring.application.name} specific to DEV envoirenment

spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/teste
   username: postgres
   password: postgres